[package]
name = "IndyVotingAppTEE"
version = "0.1.0"
authors = ["Daniel Ananth <dananth@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
optee-teec = "0.0.1"
indy = "1.6.7"
serde_json = "1.0.61"